website/blog/urls.py
from django.urls import path

from .filter import blog_Filter
from . import views

urlpatterns = [
    path("", views.BlogView.as_view(), name="home"),
    path("view/<uuid:pk>/", views.UserBlogView.as_view(), name="view"),
    path("blog/<uuid:pk>/", views.BlogDetailView.as_view(), name="blog"),
    path("create/", views.BlogCreateView.as_view(), name="blog_create"),
    path("blog/<uuid:pk>/update", views.BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<uuid:pk>/delete", views.BlogDeleteView.as_view(), name="blog-delete"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("user/", include("accounts.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("__debug__", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/blog/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

# Create your models here.


class Posts(models.Model):
    STATUS = (
        ("Draft", "Draft"),
        ("Publish", "Publish"),
        ("Private", "Private"),
    )
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    blog_id = models.CharField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        primary_key=True,
        max_length=50,
    )
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    last_modified_date = models.DateTimeField(auto_now=True, editable=False)
    post_image = models.ImageField(upload_to="blogs", null=True)
    content = RichTextField(blank=True)
    tag = models.CharField(max_length=50)
    Status = models.CharField(max_length=30, choices=STATUS, default="Private")

    def __str__(self) -> str:
        return f"{self.blog_id} -> {self.title}"

    class Meta:
        db_table = "blog_Posts"
        managed = True
        verbose_name = "Post"
        verbose_name_plural = "Posts"


class Comments(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    comment = models.TextField()
    time = models.DateTimeField(auto_now=True)
    blog = models.ForeignKey(to=Posts, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name} -> {self.blog}"

    class Meta:
        ordering = ("-time",)


class Tags(models.Model):
    tagname = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self) -> str:
        return self.tagname

    class Meta:
        db_table = "blog_tags"
        managed = True
        verbose_name = "Tags"
        verbose_name_plural = "Tagss"

website/templates/users/login.html
<div>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div>
            <p>
                <b>
                    {{field.label}}
                </b> {{field}}

            </p>
        </div>

        {% endfor %}
        <p>
            {% for err in form.password.errors %}
            {{err}}
            {% endfor %}
        </p>
        <button type="submit">Login</button>
    </form>
</div>

website/templates/users/password-reset-complete.html
{% extends "base.html" %}

{% block title %}
password reset complete
{% endblock title %}

{% block content %}
<div class="container">
    <!-- Extra space -->
    <!-- <div class="h-100px d-none d-lg-block"></div> -->
    <div class="row py-sm-5">
        <!-- Error 404 START -->
        <div class="col-lg-8 mx-auto">
            <h2 class="mb-2 h1">Password reset complete...</h2>
            <p>Your password has been set. You may go ahead and log in now..</p>
            <!-- Button -->
            <a class="btn btn-primary-soft btn-sm" href="{% url 'login' %}">Got to Login</a>
        </div>
    </div>
    <!-- Extra space -->
    <div class="h-100px d-none d-lg-block"></div>
    <!-- Row END -->
</div>
{% endblock content %}

website/templates/users/password-reset-done.html
{% extends "base.html" %}

{% block title %}
password reset sent
{% endblock title %}

{% block content %}
<div class="container">
    <!-- Extra space -->
    <!-- <div class="h-100px d-none d-lg-block"></div> -->
    <div class="row py-sm-5">
        <!-- Error 404 START -->
        <div class="col-lg-8 mx-auto">
            <h2 class="mb-2 h1">Password reset sent</h2>
            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should
                receive them shortly.</p>
            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
                your spam
                folder.</p>
            <!-- Button -->
            <a class="btn btn-primary-soft btn-sm" href="{% url 'login' %}">Got to Login</a>
        </div>
    </div>
    <!-- Extra space -->
    <div class="h-100px d-none d-lg-block"></div>
    <!-- Row END -->

</div>
{% endblock content %}

website/templates/users/password-reset-set.html
{% extends "base.html" %}

{% block title %}
set password
{% endblock title %}

{% block content %}
<div class="container">

    {% if form %}
    <div class="row g-4">
        <!-- Main content START -->
        <div class="col-lg-8 mx-auto">
            <div class="vstack py-0 tab-content">

                <!-- Change your password START -->
                <div class="card card-body rounded-3 p-4">
                    <!-- Title START -->
                    <h2 class="">
                        Enter new password
                    </h2>
                    <h6 class="mb-0">Please enter your new password twice so we can verify you typed it in correctly.
                    </h6>

                    <!-- Title START -->
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mt-2">
                                <label class="form-label">New password</label>
                                <!-- Input group -->
                                <div class="input-group">
                                    <input class="form-control fakepassword" type="password"
                                        placeholder="Enter new password" name="new_password1">
                                    <span class="input-group-text p-0">
                                        <i class="fakepasswordicon fa-solid fa-eye-slash cursor-pointer p-2 w-40px"></i>
                                    </span>
                                </div>
                            </div>

                            <div class="mt-3">
                                <label class="form-label">Confirm Password</label>
                                <!-- Input group -->
                                <div class="">
                                    <input
                                        class="form-control {% if form.new_password2.errors %} is-invalid {% endif %}"
                                        type="password" name="new_password2"
                                        value="{{form.new_password2.value|default:''}}">
                                </div>
                                {% for err in form.new_password2.errors %}
                                <small class="form-text text-danger">
                                    {{err}}
                                </small>
                                {% endfor %}
                            </div>
                            <div class="mt-3">
                                <button type="submit" class="btn btn-success btn-sm">Reset My Password</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Card END -->
            </div>
        </div>
        <!-- Main content END -->
    </div> <!-- Row END -->

    {% else %}
    <div class="row py-sm-5">
        <!-- Error 404 START -->
        <div class="col-lg-8 mx-auto">
            <h2 class="mb-2 h1">Password reset unsuccessful</h2>
            <p>The password reset link was invalid, possibly because it has already been used. Please request a new
                password reset.</p>
            <!-- Button -->
            <a class="btn btn-primary-soft btn-sm" href="{% url 'password-reset' %}">new request</a>
        </div>
    </div>
    {% endif %}
</div>


{% endblock content %}

website/templates/users/password-reset.html
{% extends "base.html" %}

{% block title %}
Passwor Reset
{% endblock title %}

{% block content %}
<div class="container">

    <div class="row g-4">
        <!-- Main content START -->
        <div class="col-lg-8 mx-auto">
            <div class="vstack py-0 tab-content">
                <!-- Change your password START -->
                <div class="card card-body rounded-3 p-4">
                    <!-- Title START -->
                    <h2 class="">
                        Password reset
                    </h2>
                    <p class="mb-0">Forgotten your password?
                        Enter your email address below, and we’ll email instructions for setting a new one
                        .</p>

                    <!-- Title START -->
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="" class="form-label">Email</label>
                                <input type="email" class="form-control" name="email" placeholder="abc@mail.com"
                                    required value="{{form.email.value|default:''}}">
                                {% for err in form.email.errors %}
                                <small id="emailHelpId" class="form-text text-danger">
                                    {{err}}
                                </small>
                                {% endfor %}

                            </div>
                            <button type="submit" class="btn btn-success btn-sm">Reset My Password</button>
                        </form>
                    </div>
                </div>
                <!-- Card END -->
            </div>
        </div>
        <!-- Main content END -->
    </div> <!-- Row END -->
</div>



{% endblock content %}

website/templates/users/password.html
{% extends "base.html" %}


{% block content %}

<div class="container">

  <div class="row g-4">
    <!-- Main content START -->
    <div class="col-lg-8 mx-auto">
      <div class="vstack py-0 tab-content">
        <!-- Change your password START -->
        <div class="card">
          <!-- Title START -->
          <div class="card-header border-0 pb-0">
            <h5 class="card-title">Change your password</h5>
            <p class="mb-0">See resolved goodness felicity shy civility domestic had but.</p>
          </div>
          <!-- Title START -->
          <div class="card-body">
            <!-- Settings START -->
            <form class="row g-3" method="post" action="">
              {% csrf_token %}
              <!-- Current password -->
              <div class="col-12">
                <label class="form-label">Current password</label>

                <input type="password" class="form-control {% if form.old_password.errors %} is-invalid {% endif %}"
                  placeholder="" name="old_password" value="{{form.old_password.value|default:''}}">

                {% for err in form.old_password.errors %}
                <small class="text-danger"> {{err}} </small>
                {% endfor %}
              </div>
              <!-- New password -->
              <div class="col-12">
                <label class="form-label">New password</label>
                <!-- Input group -->
                <div class="input-group">
                  <input class="form-control fakepassword" type="password" id="psw-input"
                    placeholder="Enter new password" name="new_password1">
                  <span class="input-group-text p-0">
                    <i class="fakepasswordicon fa-solid fa-eye-slash cursor-pointer p-2 w-40px"></i>
                  </span>
                </div>

              </div>
              <!-- Confirm password -->
              <div class="col-12">
                <label class="form-label">Confirm password</label>
                <input type="password" class="form-control {% if form.new_password2.errors %} is-invalid {% endif %}"
                  placeholder="" name="new_password2">
                {% for err in form.new_password2.errors %}
                <small> {{err}} </small>
                {% endfor %}
              </div>
              <!-- Button  -->
              <div class="col-12 text-end">
                <button type="submit" class="btn btn-primary-soft mb-0">Update password</button>
              </div>
            </form>
            <!-- Settings END -->
          </div>
        </div>
        <!-- Card END -->
      </div>
    </div>
    <!-- Main content END -->
  </div> <!-- Row END -->
</div>

{% endblock content %}

website/templates/users/password_success.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <!-- Extra space -->
    <div class="h-100px d-none d-lg-block"></div>
    <div class="row align-items-center text-center py-sm-5">
        <!-- Error 404 START -->
        <div class="col-lg-8 mx-auto">
            <h2 class="mb-2 h1">Password change successfully</h2>
            <p>Your password was changed.</p>
            <!-- Button -->
            <a class="btn btn-primary-soft btn-sm" href="{% url 'user' %}">Got to home page</a>
        </div>
    </div>
    <!-- Extra space -->
    <div class="h-100px d-none d-lg-block"></div>
    <!-- Row END -->



</div>
{% endblock content %}

website/templates/users/post-view.html
{% extends "base.html" %}

{% block content %}

<div class="container">

    <div class="row mx-5">
        <!-- Main content START -->
        <div class="col">
            <div class="vstack gap-4">
                <!-- Blog single START -->
                <div class="card card-body">
                    <img class="rounded" src="{{user_post.post_image.url}}" alt="">

                    <div class="mt-4">
                        <!-- Tag -->
                        <a href="#" class="badge bg-success bg-opacity-10 text-success mb-2 fw-bold">
                            {{user_post.tag}}
                        </a>
                        <!-- Title info -->
                        <h1 class="mb-2 h2"> {{user_post.title}}.</h1>
                        <ul class="nav nav-stack gap-3 align-items-center">
                            <li class="nav-item">
                                <div class="nav-link">
                                    by <a href="#" class="text-reset btn-link"> {{user_post.author}} </a>
                                </div>
                            </li>
                            <li class="nav-item"> <i class="bi bi-calendar-date pe-1"></i>
                                {{user_post.created_date.date}}
                            </li>
                        </ul>
                        <!-- description -->
                        <p class="mt-4">{{user_post.content|safe}} </p>
                    </div>
                </div>
                <!-- Card END -->
                <!-- Comments START -->
                <div class="card">
                    <div class="card-header pb-0 border-0">
                        <h4>{{user_post.comments_set.count}} comments </h4>
                    </div>
                    <div class="card-body">
                        <!-- Comments START -->
                        <!-- Comment level 1-->
                        {% for comment in user_post.comments_set.all %}
                        <div class="my-4 d-flex ps-3">
                            <div>
                                <div class="mb-2 d-sm-flex">
                                    <h6 class="m-0 me-2"> {{comment.name}} </h6>
                                    <span class="me-3 small"> {{comment.time}} </span>
                                </div>
                                <p> {{comment.comment}} </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- Blog single END -->
            </div>
        </div>
        <!-- Main content END -->
    </div> <!-- Row END -->
</div>

{% endblock content %}

website/templates/users/settings.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<!-- Container START -->
<div class="container">


  <!-- Main content START -->
  <div class="vstack gap-4">

    <!-- Account setting tab START -->
    <div class="tab-pane show active fade" id="nav-setting-tab-1">
      {% for msg in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        <strong>Sucess</strong> {{msg}}
      </div>
      {% endfor %}

      <!-- Account settings START -->
      <div class="card mb-4">

        <!-- Title START -->
        <div class="card-header border-0 pb-0">
          <h1 class="h5 card-title">Account Settings</h1>

        </div>
        <!-- Card header START -->
        <!-- Card body START -->
        <div class="card-body">
          <!-- Form settings START -->
          <form class="row g-3" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in user_form %}
            <div class="col-sm-6">
              <label class="form-label">{{field.label}}</label>
              {{field}}

              <small class="text-danger">
                {% for error in field.errors %}
                {{error}}
                {% endfor %}
              </small>

            </div>
            {% endfor %}

            {% for setting_field in user_setting %}
            <div class="col-sm-6">
              <label class="form-label">{{setting_field.label}}</label>
              {{setting_field}}
            </div>
            {% endfor %}
            <br>
            {% for profile_field in user_profile %}
            <div class="col-sm-6">
              <label for="form-label">{{profile_field.label}}</label>
              {{profile_field}}
            </div>
            {% endfor %}


            <!-- Button  -->
            <div class="col-12 text-end">
              <button type="submit" class="btn btn-sm btn-primary mb-0">Save changes</button>
            </div>
          </form>
          <!-- Settings END -->
        </div>
        <!-- Card body END -->
      </div>
      <!-- Account settings END -->
    </div>

  </div>

</div>
<!-- Container END -->
{% endblock content %}

website/templates/users/sign-in.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock title %}

{% block content %}


<!-- Container START -->
<div class="container">
  <div class="row justify-content-center align-items-center vh-100 py-5">
    <!-- Main content START -->
    <div class="col-sm-10 col-md-8 col-lg-7 col-xl-6 col-xxl-5">
      <!-- Sign in START -->
      <div class="card card-body text-center p-4 p-sm-5">
        <!-- Title -->
        <h1 class="mb-2">Sign in</h1>
        <p class="mb-0">Don't have an account?<a href="{% url 'register' %}"> Click here to sign up</a></p>
        <!-- Form START -->
        <form class="mt-sm-4" action="" method="post">
          {% csrf_token %}

          <!-- Email -->
          <div class="mb-3 input-group-lg">
            <input type="text" class="form-control" placeholder="Enter username" name="username">
            <small class="text-start text-danger">
            </small>
          </div>
          <!-- New password -->
          <div class="mb-3 position-relative">
            <!-- Password -->
            <div class="input-group input-group-lg">
              <input class="form-control fakepassword" type="password" id="psw-input" placeholder="Enter new password"
                name="password">
              <span class="input-group-text p-0">
                <i class="fakepasswordicon fa-solid fa-eye-slash cursor-pointer p-2 w-40px"></i>
              </span>
            </div>

            <div class="d-flex mt-1">
              <div id="pswmeter-message" class="rounded"></div>
              <!-- Password message notification -->
              <div class="ms-auto text-danger">
                {% for err in form.password.errors %}
                {{err}}<i class="bi bi-info-circle ps-1"></i>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="mb-3 d-sm-flex justify-content-end">
            <a href="{% url 'password-reset' %}">Forgot password?</a>
          </div>
          <!-- Button -->
          <div class="d-grid"><button type="submit" class="btn btn-lg btn-primary">Login</button>
          </div>
          <!-- Copyright -->
          <p class="mb-0 mt-3">©2022 All rights reserved</p>
        </form>
        <!-- Form END -->
      </div>
      <!-- Sign in START -->
    </div>
  </div> <!-- Row END -->
</div>
<!-- Container END -->
{% endblock content %}

website/templates/users/sign-up.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock title %}


{% block content %}

<!-- Container START -->
<div class="container">
  <div class="row justify-content-center align-items-center vh-100 py-5">
    <!-- Main content START -->
    <div class="col-sm-10 col-md-8 col-lg-7 col-xl-6 col-xxl-5">
      <!-- Sign up START -->
      <div class="card card-body rounded-3 p-4 p-sm-5">
        <div class="text-center">
          <!-- Title -->
          <h1 class="mb-2">Sign up</h1>
          <span class="d-block">Already have an account? <a href="{% url 'login' %}">Sign in here</a></span>
        </div>
        <!-- Form START -->
        <form class="mt-4" action="" method="post">
          {% csrf_token %}
          <!-- user name -->
          <div class="mb-3 input-group-lg">
            <input type="text" class="form-control {% if form.username.errors %} is-invalid {% endif %}"
              placeholder="Enter user name" name="username" value="{{form.username.data|default:''}}">
            <small class="text-danger">
              {% for error in form.username.errors %}
              {{error}}
              {% endfor %}
            </small>
          </div>
          <!-- Email -->
          <div class="mb-3 input-group-lg">
            <input type="email" class="form-control {% if form.email.errors %} is-invalid {% endif %}"
              placeholder="Enter email" name="email" value="{{form.email.data|default:''}}">
            <small class="text-danger">
              {% for error in form.email.errors %}
              {{error}}
              {% endfor %}
            </small>
          </div>
          <!-- New password -->
          <div class="mb-3 position-relative">
            <!-- Input group -->
            <div class="input-group input-group-lg">
              <input class="form-control fakepassword" type="password" id="psw-input" placeholder="Enter new password"
                name="password" value="{{form.password.data|default:''}}">
              <span class="input-group-text p-0">
                <i class="fakepasswordicon fa-solid fa-eye-slash cursor-pointer p-2 w-40px"></i>
              </span>
            </div>

          </div>
          <!-- Confirm password -->
          <div class="mb-3 input-group-lg">
            <input class="form-control {% if form.conf_password.errors %} is-invalid {% endif %}" type="password"
              placeholder="Confirm password" name="conf_password" value="{{form.conf_password.data|default:''}}">
          </div>

          <!-- Pswmeter -->
          <div id="pswmeter" class="mt-2"></div>
          <div class="d-flex mt-1">
            <div id="pswmeter-message" class="rounded"></div>
            <!-- Password message notification -->
            <div class="ms-auto text-danger">
              {% for error in form.conf_password.errors %}
              {{error}}
              {% endfor %}
            </div>
          </div>
          <!-- Button -->
          <div class="d-grid mt-2"><button type="submit" class="btn btn-lg btn-primary">Sign me up</button></div>
          <!-- Copyright -->
          <p class="mb-0 mt-3 text-center">©2022
            <span>Blog.</span> All rights reserved
          </p>
        </form>
        <!-- Form END -->
      </div>
      <!-- Sign up END -->
    </div>
  </div> <!-- Row END -->
</div>
<!-- Container END -->


{% endblock content %}